object EhLibLanguageConsts: TEhLibLanguageConsts_ROU
  Language = 'Romanian'

  ClearSelectedCells = 'Șterge celulele selectate?'
  InvalidTextFormat = 'Format text invalid'
  InvalidVCLDBIFFormat = 'Format VCLDBIF invalid'
  ErrorDuringInsertValue = 'Eroare la inserarea valorii:'
  IgnoreError = 'Ignoră eroarea?'
  TabularInformation = 'Informații tabelare'
  PageOfPages = 'Pagina %d din %d'
  Preview = 'Previzualizare'
  FieldNameNotFound = 'Numele câmpului ''%s'' nu a fost găsit'
  FindDialogStringNotFoundMessage = 'Șirul "%s" nu a fost găsit.'
  VisibleColumns = 'Coloane vizibile'
  Cut = 'Taie'
  Copy = 'Copiază'
  Paste = 'Lipește'
  Delete = 'Șterge'
  SelectAll = 'Selectează tot'

  STFilterListItem_Empties = 'Goală'
  STFilterListItem_NotEmpties = 'Nu este goală'
  STFilterListItem_All = 'Toate'
  STFilterListItem_SelectAll = 'Selectează tot'
  STFilterListItem_ClearFilter = 'Șterge filtrul'
  STFilterListItem_ClearFilterInColumn = 'Șterge filtrul din coloană'
  STFilterListItem_SortingByAscend = 'Ordonează crescător'
  STFilterListItem_SortingByDescend = 'Ordonează descrescător'
  STFilterListItem_ApplyFilter = 'Aplică filtrul'
  STFilterListItem_CustomFilter = 'Personalizat...'
  STFilterListItem_ShowFilterWindow = 'Show filter window ...'
  STFilterListItem_HideSelectedColumns = 'Hide selected columns'
  STFilterListItem_HideColumn = 'Hide column'

  SimpFilter_equals = 'egal'
  SimpFilter_does_not_equal = 'nu este egal'
  SimpFilter_is_greater_than = 'este mai mare decât'
  SimpFilter_is_greater_than_or_equal_to = 'este mai mare sau egal cu'
  SimpFilter_is_less_than = 'este mai mic decât'
  SimpFilter_is_less_than_or_equal_to = 'este mai mic sau egal cu'
  SimpFilter_begins_with = 'începe cu'
  SimpFilter_does_not_begin_with = 'nu începe cu'
  SimpFilter_ends_with = 'se termină cu'
  SimpFilter_does_not_end_with = 'nu se termină cu'
  SimpFilter_contains = 'conține'
  SimpFilter_does_not_contain = 'nu conține'
  SimpFilter_like = 'ca'
  SimpFilter_not_like = 'nu ca'
  SimpFilter_in_list = 'în listă'
  SimpFilter_not_in_list = 'nu în listă'
  SimpFilter_is_blank = 'este gol'
  SimpFilter_is_not_blank = 'nu este gol'

  GroupingPanelText = 'Trageți antetul unei coloane aici pentru a grupa după acea coloană'

  NoDataEh = '<Fără înregistrări>'
  CalculatorError = 'Eroare'

  QuoteIsAbsentEh = 'Lipsă ghilimele: '
  LeftBracketExpectedEh = '''('' așteptat: '
  RightBracketExpectedEh = ''')'' așteptat: '
  ErrorInExpressionEh = 'Eroare în expresie: '
  UnexpectedExpressionBeforeNullEh = 'Expresie neașteptată înainte de Null: '
  UnexpectedExpressionAfterOperatorEh = 'Expresie neașteptată după operator: '
  IncorrectExpressionEh = 'Expresie incorectă: '
  UnexpectedANDorOREh = 'AND sau OR neașteptat: '

  GridSelectionInfo_Sum = 'Sumă'
  GridSelectionInfo_Cnt = 'Număr'
  GridSelectionInfo_Evg = 'Medie'
  GridSelectionInfo_Min = 'Minim'
  GridSelectionInfo_Max = 'Maxim'
  CellCountEh = 'Număr celule'

  DBGridEhGroupingFooter_Sum = 'Sumă'
  DBGridEhGroupingFooter_Count = 'Număr'
  DBGridEhGroupingFooter_Avg = 'Medie'
  DBGridEhGroupingFooter_Max = 'Maxim'
  DBGridEhGroupingFooter_Min = 'Minim'
  DBGridEhGroupingFooter_Empty = '(Gol)'

  FirstRecordEh = 'Prima înregistrare'
  PriorRecordEh = 'Înregistrarea anterioară'
  NextRecordEh = 'Înregistrarea următoare'
  LastRecordEh = 'Ultima înregistrare'
  InsertRecordEh = 'Inserează înregistrare'
  DeleteRecordEh = 'Șterge înregistrare'
  EditRecordEh = 'Editează înregistrare'
  PostEditEh = 'Salvează modificările'
  CancelEditEh = 'Anulează modificările'
  ConfirmCaptionEh = 'Confirmă'
  RefreshRecordEh = 'Reîncarcă datele'

  DeleteMultipleRecordsQuestionEh = 'Ștergeți %d înregistrări selectate?'
  DeleteAllRecordsQuestionEh = 'Ștergeți toate înregistrările?'

  DuplicateVarNameEh = 'O variabilă cu numele ''%s'' există deja în colecție'

  SearchPanelEditorPromptText = 'Caută...'
  UnsupportedFieldTypeEh = 'Tip de câmp nesuportat (%s) în câmpul %s'

  SearchPanelApplyFilterEh = 'Afișează înregistrările unde textul este găsit'
  SearchPanelCancelFilterEh = 'Anulează filtrul și șterge textul căutării'
  SearchPanelFindNextEh = 'Găsește următorul'
  SearchPanelFindPrevEh = 'Găsește precedentul'
  SearchPanelOptionsEh = 'Afișează opțiunile de căutare'

  SortingByThisColumnIsNotPossibleEh = 'Sortarea după această coloană nu este posibilă'
  GroupingByThisColumnIsNotPossibleEh = 'Gruparea după această coloană nu este posibilă'

  FindItemNameAllEh = '<Toate>'

  ElapsedTimeEh = 'Timp scurs'
  PivotDataBuildingInProgressEh = 'Construirea datelor pivot este în desfășurare...'
  PressESCToCancelEh = 'Apăsați ESC pentru a anula'

  GrandTotalEh = 'Total general'
  TotalEh = 'Total'
  PivotValueFieldDisplayNameEh = '(Valoare)'
  PivotRowsEh = 'Rânduri'
  PivotColumnsEh = 'Coloane'
  PivotValuesEh = 'Valori'
  PivotDataIsNotLoadedEh = '<Datele nu sunt încărcate>'

  PivotSliceNonDisplayNameEh = 'Nicio'
  PivotSliceYearDisplayNameEh = 'An'
  PivotSliceQuarterDisplayNameEh = 'Trimestru'
  PivotSliceMonthDisplayNameEh = 'Lună'
  PivotSliceWeekDisplayNameEh = 'Săptămână'
  PivotSliceDayDisplayNameEh = 'Zi'
  PivotSliceHourDisplayNameEh = 'Oră'
  PivotSliceMinDisplayNameEh = 'Minut'
  PivotSliceSecDisplayNameEh = 'Secundă'
  PivotSliceMSecDisplayNameEh = 'Milisecundă'

  PivotSumFunctionNon = 'Nicio'
  PivotSumFunctionSum = 'Sumă'
  PivotSumFunctionCount = 'Număr'
  PivotSumFunctionAvg = 'Medie'
  PivotSumFunctionMax = 'Maxim'
  PivotSumFunctionMin = 'Minim'
  PivotSumFunctionCountDistinct = 'Număr distinct'
  PivotSumFunctionProduct = 'Produs'
  PivotSumFunctionStDev = 'DevSt'
  PivotSumFunctionStDevp = 'DevStp'
  PivotSumFunctionVar = 'Var'
  PivotSumFunctionVarp = 'Varp'
  PivotSumFunctionCustom = 'Personalizat'

  PlannerResourceUnassignedEh = 'Nerepartizat'
  PlannerNextEventEh = 'Eveniment următor'
  PlannerPriorEventEh = 'Eveniment anterior'
  PlannerDeletePlanItemEh = 'Șterge eveniment?'
  PlannerPeriodFromEh = 'De la'
  PlannerPeriodToEh = 'Până la'
  PlannerWeekTextEh = 'SĂPTĂMÂNĂ'
  PlannerEndTimeBeforeStartTimeEh = 'Ora de sfârșit este înainte de ora de început'

  OKButtonEh = 'OK'
  CancelButtonEh = 'Anulare'

  GridLoadingModeTextEh = 'Se încarcă...'

  SearchScopeEh = 'Domeniul căutării'
  CurrentColumnEh = 'Coloana curentă'
  TheEntireGridEh = 'Întregul tabel'
  CaseSensitiveEh = 'Sensibil la majuscule'
  WholeWordsEh = 'Cuvinte întregi'
  BeginsWithEh = 'Începe cu'
  CloseInBracketsEh = '(Închide)'

  LabelColumnEh = 'Coloană etichetă'
  DataColumnEh = 'Coloană date'

  TodayEh = 'Astăzi'

  PreviewForm_Caption = 'Previzualizare'
  PreviewForm_Print_Hint = 'Imprimare'
  PreviewForm_Print_Caption = 'Imprimă'
  PreviewForm_PrinterSetupDialog_Hint = 'Configurare imprimantă'
  PreviewForm_PrinterSetupDialog_Caption = 'Configurare imprimantă'
  PreviewForm_Scale_Hint = 'Scalare'
  PreviewForm_Scale_Caption = 'Scalare'
  PreviewForm_PrevPage_Hint = 'Pagina anterioară'
  PreviewForm_PrevPage_Caption = 'Anterior'
  PreviewForm_NextPage_Hint = 'Pagina următoare'
  PreviewForm_NextPage_Caption = 'Următor'
  PreviewForm_Stop_Caption = 'Oprire'
  PreviewForm_Close_Hint = 'Închide previzualizarea'
  PreviewForm_Close_Caption = 'Închide'
  PreviewForm_MenuPageWidth = 'Lățime pagină'
  PreviewForm_MenuFullPage = 'Întreaga pagină'

  PrnDBGridEhSetupDialog_Caption = 'Configurare imprimantă'
  PrnDBGridEhSetupDialog_Margins = '&Margini '
  PrnDBGridEhSetupDialog_Top = '&Sus'
  PrnDBGridEhSetupDialog_Bottom = '&Jos'
  PrnDBGridEhSetupDialog_Left = 'S&tânga'
  PrnDBGridEhSetupDialog_Right = '&Dreapta'
  PrnDBGridEhSetupDialog_StretchLongLines = '&Extinde liniile lungi'
  PrnDBGridEhSetupDialog_PrinterSetup = 'C&onfigurare imprimantă'
  PrnDBGridEhSetupDialog_Colored = '&Colorat'
  PrnDBGridEhSetupDialog_ScaleWholeGrid = 'Scalați întreaga &grilă'
  PrnDBGridEhSetupDialog_ChangeColumnWidths = 'Sc&himbați lățimea coloanelor'
  PrnDBGridEhSetupDialog_FitWidthToPage = '&Potrivește lățimea pe o pagină'
  PrnDBGridEhSetupDialog_OptimalColWidths = '&Lățimi optime ale coloanelor'

  PlannerItemForm_Caption = 'Element Planificator'
  PlannerItemForm_Item_Title = 'Titlu:'
  PlannerItemForm_Item_StartTime = 'Ora de început:'
  PlannerItemForm_Item_EndTime = 'Ora de sfârșit:'
  PlannerItemForm_AllDayCheck = 'Eveniment pe tot parcursul zilei'
  PlannerItemForm_Resource = 'Resursă:'

  PictureEditorDialog_Caption = 'Editor de imagini'
  PictureEditorDialog_Load = '&Încarcă...'
  PictureEditorDialog_Save = '&Salvează...'
  PictureEditorDialog_Clear = '&Șterge'
  PictureEditorDialog_Cut = 'Taie'
  PictureEditorDialog_Copy = 'Copiază'
  PictureEditorDialog_Paste = 'Lipește'
  PictureEditorDialog_ZoomIn = 'Mărește'
  PictureEditorDialog_ZoomOut = 'Micșorează'
  PictureEditorDialog_Reset = 'Resetează'

  EditPivotField_Caption = 'Funcție sumară'
  EditPivotField_AggrFunc = 'Funcție sumară:'
  EditPivotField_DisplayFormat = 'Format afișare:'

  DBGridEhSimpleFilterDialog_Caption = 'Filtru personalizat'
  DBGridEhSimpleFilterDialog_ShowRecordsWhere = 'Afișează înregistrările unde:'
  DBGridEhSimpleFilterDialog_OneCharWildcardInfo = 'Folosiți "_" pentru a reprezenta orice caracter unic'
  DBGridEhSimpleFilterDialog_SeveralCharsWildcardInfo = 'Folosiți "%" pentru a reprezenta orice serie de caractere'
  DBGridEhSimpleFilterDialog_Or_Caption = '&Sau'
  DBGridEhSimpleFilterDialog_And_Caption = '&Și'

  DBGridEhFindDlg_Caption = 'Găsiți text'
  DBGridEhFindDlg_FindWhat = 'Ce să g&ăsiți:'
  DBGridEhFindDlg_FindIn = 'Găsiți &în:'
  DBGridEhFindDlg_Match = 'Potriviți:'
  DBGridEhFindDlg_Search = 'Căut&are:'
  DBGridEhFindDlg_FindInTree = 'Găsiți în arbore:'
  DBGridEhFindDlg_FindNext = '&Găsiți următorul'
  DBGridEhFindDlg_Close = 'Închide'
  DBGridEhFindDlg_FromAnyPart = 'Din orice parte a câmpului'
  DBGridEhFindDlg_WholeField = 'Întregul câmp'
  DBGridEhFindDlg_FromBeginning = 'De la începutul câmpului'
  DBGridEhFindDlg_Direction_Up = 'Sus'
  DBGridEhFindDlg_Direction_Down = 'Jos'
  DBGridEhFindDlg_Direction_All = 'Toate'
  DBGridEhFindDlg_MatchCase = 'Potrivire majuscule &minuscule'
  DBGridEhFindDlg_MatchFormat = 'Potrivire F&ormat'
  DBGridEhFindDlg_TreeRange_InAllNodes = 'În toate nodurile'
  DBGridEhFindDlg_TreeRange_InExpandedNodes = 'În nodurile extinse'
  DBGridEhFindDlg_TreeRange_InCurrentLevel = 'În nivelul curent'
  DBGridEhFindDlg_TreeRange_InCurrentNode = 'În nodul curent'

  PrintPageSetupDialog_Caption = 'Configurare pagină'
  PrintPageSetupDialog_Page = 'Pagină'
  PrintPageSetupDialog_Orientation = 'Orientare'
  PrintPageSetupDialog_Scaling = 'Scalare'
  PrintPageSetupDialog_Portrait = 'Portret'
  PrintPageSetupDialog_Landscape = 'Peisaj'
  PrintPageSetupDialog_PrNormalSize =  '% dimensiune normală'
  PrintPageSetupDialog_PageWideBy = 'pagini lățime de'
  PrintPageSetupDialog_tall = 'înălțime'
  PrintPageSetupDialog_AdjustTo = 'Ajustați la'
  PrintPageSetupDialog_FitTo = 'Potrivește la'
  PrintPageSetupDialog_Margins = 'Margini'
  PrintPageSetupDialog_Left = 'Stânga'
  PrintPageSetupDialog_Top = 'Sus'
  PrintPageSetupDialog_Bottom = 'Jos'
  PrintPageSetupDialog_Right = 'Dreapta'
  PrintPageSetupDialog_Header = 'Antet'
  PrintPageSetupDialog_Footer = 'Subsol'
  PrintPageSetupDialog_HeaderFooter = 'Antet/Subsol'
  PrintPageSetupDialog_ChangeFont = 'Schimbă fontul'
  PrintPageSetupDialog_FontAbr = 'F'
  PrintPageSetupDialog_InsertPageNo_Hint = 'Inserează numărul paginii'
  PrintPageSetupDialog_InsertPageNo_Abr = 'Pn'
  PrintPageSetupDialog_InsertPages_Hint = 'Inserează pagini'
  PrintPageSetupDialog_InsertPages_Abr = 'Ps'
  PrintPageSetupDialog_InsertDate_Hint = 'Inserează data'
  PrintPageSetupDialog_InsertDate_Abr = 'D'
  PrintPageSetupDialog_InsertShortDate_Hint = 'Inserează data scurtă'
  PrintPageSetupDialog_InsertShortDate_Abr = 'Ds'
  PrintPageSetupDialog_InsertLongDate_Hint = 'Inserează data lungă'
  PrintPageSetupDialog_InsertLongDate_Abr = 'Dl'
  PrintPageSetupDialog_InsertTime_Hint = 'Inserează timpul'
  PrintPageSetupDialog_InsertTime_Abr = 'T'
  PrintPageSetupDialog_PageHeader = 'Antetul paginii'
  PrintPageSetupDialog_PageFooter = 'Subsolul paginii'
  PrintPageSetupDialog_Center = 'Centrează'

  CustomizeColumnsDialog = 'Personalizează coloanele ...'
  DBGridEhCustomizeColumnsDialog_VisibleColumns = 'Coloane vizibile'
  DBGridEhCustomizeColumnsDialog_HiddenColumns = 'Coloane ascunse'
  DBGridEhCustomizeColumnsDialog_Caption = 'Setare coloane'
  DBGridEhCustomizeColumnsDialog_ColumnName = 'Nume'
  DBGridEhCustomizeColumnsDialog_ColumnWidth = 'Lățime'
  DBGridEhCustomizeColumnsDialog_SetWidth_Hint = 'Setați lățimea'
  DBGridEhCustomizeColumnsDialog_MoveUp_Hint = 'Mută în sus'
  DBGridEhCustomizeColumnsDialog_MoveDown_Hint = 'Mută în jos'
  DBGridEhCustomizeColumnsDialog_Hide_Hint = 'Ascunde'
  DBGridEhCustomizeColumnsDialog_Show_Hint = 'Afișează'
  DBGridEhCustomizeColumnsDialog_EnterNumericalValue = 'Introduceți o valoare numerică'
  DBGridEhCustomizeColumnsDialog_EnterColumnWidthS = 'Lățimea(lățimile) coloanelor'

  FilterListValuesLimitExceeded = 'Prea multe valori selectate.'#13#10'Numărul de valori selectate nu poate depăși %d'
end
