object EhLibLanguageConsts: TEhLibLanguageConsts_UZB
  Language = 'Uzbekish'

  ClearSelectedCells = 'Белгиланган катак тозалансинми?'
  InvalidTextFormat = 'Матнни номаълум формати'
  InvalidVCLDBIFFormat = 'VCLDBIF формати хато'
  ErrorDuringInsertValue = 'Қийматни жойлаштиришда хато:'
  IgnoreError = 'Хатога эътибор берилмасинми?'
  TabularInformation = 'Жадвалли маълумот'
  PageOfPages = '%d-саҳифа. Жами %d саҳифа'
  Preview =  'Олдинан кўриш'
  FieldNameNotFound = 'Майдон ''%s'' топилмади'
  FindDialogStringNotFoundMessage = ' "%s" саҳифаси топилмади.'
  VisibleColumns = 'Кўринадиган устунлар'
  Cut = 'Қирқиб олиш'
  Copy = 'Нусхалаш'
  Paste = 'Жойлаштириш'
  Delete = 'Ўчириш'
  SelectAll = 'Барчасини танлаш'

  STFilterListItem_Empties = 'Бўш'
  STFilterListItem_NotEmpties = 'Бўш эмас'
  STFilterListItem_All = 'Барчаси'
  STFilterListItem_SelectAll = 'Барча элементни танлаш'
  STFilterListItem_ClearFilter = 'Филтрни тозалаш'
  STFilterListItem_ClearFilterInColumn = 'Устундаги филтрни тозалаш'
  STFilterListItem_SortingByDescend = 'Камайишга тартиблаш'
  STFilterListItem_SortingByAscend = 'Ўсишга тартиблаш'
  STFilterListItem_ApplyFilter = 'Филтрни тадбиқ қилиш'
  STFilterListItem_CustomFilter = 'Шарт...'
  STFilterListItem_ShowFilterWindow = 'Show filter window ...'
  STFilterListItem_HideSelectedColumns = 'Hide selected columns'
  STFilterListItem_HideColumn = 'Hide column'

  SimpFilter_equals              = 'тенг'
  SimpFilter_does_not_equal      = 'тенг эмас'
  SimpFilter_is_greater_than      = 'катта'
  SimpFilter_is_greater_than_or_equal_to = 'катта ёки тенг'
  SimpFilter_is_less_than        = 'кичик'
  SimpFilter_is_less_than_or_equal_to = 'кичик ёки тенг'
  SimpFilter_begins_with         = 'бошланиши...'
  SimpFilter_does_not_begin_with = 'бошланмайди...'
  SimpFilter_ends_with           = 'тугаши шундай'
  SimpFilter_does_not_end_with   = 'шундай тугамайди'
  SimpFilter_contains            = 'таркибида бор'
  SimpFilter_does_not_contain    = 'таркибда йўқ'
  SimpFilter_like                = 'ўхшаш'
  SimpFilter_not_like            = 'ўхшамайди'
  SimpFilter_in_list             = 'рўйхатда'
  SimpFilter_not_in_list         = 'рўйхатда йўқ'
  SimpFilter_is_blank            = 'бўш'
  SimpFilter_is_not_blank        = 'бўш эмас'

  GroupingPanelText = 'Гуруҳламоқчи бўлган устунни бу ерга судранг'

  NoDataEh = 'Қийматсиз'

  QuoteIsAbsentEh = 'Отсутствует кавычка: '
  LeftBracketExpectedEh = '''('' пропущена: '
  RightBracketExpectedEh = ''')'' пропущена: '
  ErrorInExpressionEh = 'Ошибка в выражении: '
  UnexpectedExpressionBeforeNullEh = 'Пропущено выражение перед Null: '
  UnexpectedExpressionAfterOperatorEh = 'Пропущено выражение после оператора: '
  IncorrectExpressionEh = 'Неверное выражение: '
  UnexpectedANDorOREh = 'Пропущен AND или OR: '

  GridSelectionInfo_Sum = 'Sum'
  GridSelectionInfo_Cnt = 'Count'
  GridSelectionInfo_Evg = 'Average'
  GridSelectionInfo_Min = 'Min'
  GridSelectionInfo_Max = 'Max'
  CellCountEh = 'Cell Count'

  FirstRecordEh = 'Дастлабки'
  PriorRecordEh = 'Олдинги'
  NextRecordEh = 'Кейинги'
  LastRecordEh = 'Охирги'
  InsertRecordEh = 'Қўшиш'
  DeleteRecordEh = 'Ўчириш'
  EditRecordEh = 'Тахрирлаш'
  PostEditEh = 'Сақлаш'
  CancelEditEh = 'Бекор қилиш'
  ConfirmCaptionEh = 'Тасдиқлаш'
  RefreshRecordEh = 'Янгилаш'

  DeleteMultipleRecordsQuestionEh = 'Удалить %d выбранных записей?'
  DeleteAllRecordsQuestionEh = 'Удалить все записи?'

  DuplicateVarNameEh = 'Переменная с именем ''%s'' уже присутствует в Коллекции'

  SearchPanelEditorPromptText = 'Излаш...'
  UnsupportedFieldTypeEh = 'Неподдерживаемый тип (%s) для поля %s'

  SearchPanelApplyFilterEh = 'Показать все записи, которые содержат текст'
  SearchPanelCancelFilterEh = 'Отменить фильтр и очистить строку поиска'
  SearchPanelFindNextEh = 'Искать следующее совпадение'
  SearchPanelFindPrevEh = 'Искать предыдущее совпадение'
  SearchPanelOptionsEh = 'Показать опции поиска'

  SortingByThisColumnIsNotPossibleEh = 'Сортировка по этому полю невозможна'
  GroupingByThisColumnIsNotPossibleEh = 'Группировка по этому полю невозможна'

  FindItemNameAllEh = '<Барчаси>'

  ElapsedTimeEh = 'Elapsed time'
  PivotDataBuildingInProgressEh = 'Идет создание данных для сводной таблицы...'
  PressESCToCancelEh = 'Нажмите ESC чтобы прервать'

  GrandTotalEh = 'Общий итог'
  TotalEh = 'Итог'
  PivotValueFieldDisplayNameEh = '(Значение)'
  PivotRowsEh = 'Строки'
  PivotColumnsEh = 'Столбцы'
  PivotValuesEh = 'Значения'
  PivotDataIsNotLoadedEh = '<Данные не загружены>'

  PivotSliceNonDisplayNameEh = 'Нет'
  PivotSliceYearDisplayNameEh = 'Год'
  PivotSliceQuarterDisplayNameEh = 'Квартал'
  PivotSliceMonthDisplayNameEh = 'Месяц'
  PivotSliceWeekDisplayNameEh = 'Неделя'
  PivotSliceDayDisplayNameEh = 'День'
  PivotSliceHourDisplayNameEh = 'Час'
  PivotSliceMinDisplayNameEh = 'Минута'
  PivotSliceSecDisplayNameEh = 'Секунда'
  PivotSliceMSecDisplayNameEh = 'Микросекунда'

  PivotSumFunctionNon = 'Нет'
  PivotSumFunctionSum = 'Сумма'
  PivotSumFunctionCount = 'Количество'
  PivotSumFunctionAvg = 'Среднее'
  PivotSumFunctionMax = 'Максимум'
  PivotSumFunctionMin = 'Минимум'
  PivotSumFunctionCountDistinct = 'Количество уникальных'
  PivotSumFunctionProduct = 'Произведение'
  PivotSumFunctionStDev = 'Смещенное отклонение'
  PivotSumFunctionStDevp = 'Несмещенное отклонение'
  PivotSumFunctionVar = 'Смещенная дисперсия'
  PivotSumFunctionVarp = 'Несмещенная дисперсия'
  PivotSumFunctionCustom = 'Пользовательская'

  PlannerResourceUnassignedEh = 'Не присвоен'
  PlannerNextEventEh = 'Следующее событие'
  PlannerPriorEventEh = 'Предыдущее событие'
  PlannerDeletePlanItemEh = 'Удалить событие?'
  PlannerPeriodFromEh = 'С'
  PlannerPeriodToEh = 'По'
  PlannerWeekTextEh = 'НЕДЕЛЯ'
  PlannerEndTimeBeforeStartTimeEh = 'The EndTime is before the StartTime'

  OKButtonEh = 'OK'
  CancelButtonEh = 'Бекор'

  GridLoadingModeTextEh = 'Юкланмоқда...'

  SearchScopeEh = 'Излаш сохаси'
  CurrentColumnEh = 'Жорий устун'
  TheEntireGridEh = 'Бутун жадвалдан'
  CaseSensitiveEh = 'Харф шакли эътиборли'
  WholeWordsEh = 'Бутун сўз'
  BeginsWithEh = 'Бошланиши ...'
  CloseInBracketsEh = '(Ёпиш)'

  LabelColumnEh = 'Столбец заголовков'
  DataColumnEh = 'Столбец данных'

  TodayEh = 'Бугун'

  PreviewForm_Caption = 'Предварительный просмотр'
  PreviewForm_Print_Hint = 'Печатать'
  PreviewForm_Print_Caption = 'Печатать'
  PreviewForm_PrinterSetupDialog_Hint = 'Настройка принтера'
  PreviewForm_PrinterSetupDialog_Caption = 'Настройка принтера'
  PreviewForm_Scale_Hint = 'Масштаб'
  PreviewForm_Scale_Caption = 'Масштаб'
  PreviewForm_PrevPage_Hint = 'Предыдущая страница'
  PreviewForm_PrevPage_Caption = 'Предыдущая'
  PreviewForm_NextPage_Hint = 'Следующая страница'
  PreviewForm_NextPage_Caption = 'Следующая'
  PreviewForm_Stop_Caption = 'Стоп'
  PreviewForm_Close_Hint = 'Закрыть окно предварительного просмотра'
  PreviewForm_Close_Caption = 'Закрыть'
  PreviewForm_MenuPageWidth = 'По ширине страницы'
  PreviewForm_MenuFullPage = 'Страница целиком'

  PrnDBGridEhSetupDialog_Caption = 'Настройка принтера'
  PrnDBGridEhSetupDialog_Margins = ' &Отступы '
  PrnDBGridEhSetupDialog_Top = '&Верхний'
  PrnDBGridEhSetupDialog_Bottom = '&Нижний'
  PrnDBGridEhSetupDialog_Left = '&Левый'
  PrnDBGridEhSetupDialog_Right = '&Правый'
  PrnDBGridEhSetupDialog_StretchLongLines = 'Перенос &длинных строк'
  PrnDBGridEhSetupDialog_PrinterSetup = 'Н&астройка принтера'
  PrnDBGridEhSetupDialog_Colored = '&Цвет'
  PrnDBGridEhSetupDialog_ScaleWholeGrid = 'Масштабировать всю таблицу'
  PrnDBGridEhSetupDialog_ChangeColumnWidths = 'Изменять ширину столбцов'
  PrnDBGridEhSetupDialog_FitWidthToPage = '&Умещать в ширину на листе'
  PrnDBGridEhSetupDialog_OptimalColWidths = 'Оптимальная ширина столбцов'

  PlannerItemForm_Caption = 'Событие'
  PlannerItemForm_Item_Title = 'Заголовок:'
  PlannerItemForm_Item_StartTime = 'Дата начала:'
  PlannerItemForm_Item_EndTime = 'Дата окончания:'
  PlannerItemForm_AllDayCheck = 'Весь день'
  PlannerItemForm_Resource = 'Ресурс:'

  PictureEditorDialog_Caption = 'Редактор изображений'
  PictureEditorDialog_Load = '&Из файла...'
  PictureEditorDialog_Save = '&В файл...'
  PictureEditorDialog_Clear = '&Очистить'
  PictureEditorDialog_Cut = 'Вырезать'
  PictureEditorDialog_Copy = 'Скопировать'
  PictureEditorDialog_Paste = 'Вставить'
  PictureEditorDialog_ZoomIn = 'Увеличить'
  PictureEditorDialog_ZoomOut = 'Уменьшить'
  PictureEditorDialog_Reset = 'Исх. разм.'

  EditPivotField_Caption = 'Параметры поля значений'
  EditPivotField_AggrFunc = 'Операция:'
  EditPivotField_DisplayFormat = 'Числовой формат:'

  DBGridEhSimpleFilterDialog_Caption = 'Фойдаланувчи филтри:'
  DBGridEhSimpleFilterDialog_ShowRecordsWhere = 'Фақат қиймати шундай бўлганларни кўрсатиш:'
  DBGridEhSimpleFilterDialog_OneCharWildcardInfo = 'Бу "_" ихтиёрий битта белгини билдиради'
  DBGridEhSimpleFilterDialog_SeveralCharsWildcardInfo = 'Бу "%" иктиёрий белгилар кетма-кетлигини билдиради'
  DBGridEhSimpleFilterDialog_Or_Caption = '&Ёки'
  DBGridEhSimpleFilterDialog_And_Caption = '&Ва'

  DBGridEhFindDlg_Caption = 'Излаш'
  DBGridEhFindDlg_FindWhat = '&Намуна:'
  DBGridEhFindDlg_FindIn = '&Бу ердан излаш:'
  DBGridEhFindDlg_Match = '&Мослик:'
  DBGridEhFindDlg_Search = '&Кўриш:'
  DBGridEhFindDlg_FindInTree = 'Шажарадан излаш:'
  DBGridEhFindDlg_FindNext = '&Давом этиш'
  DBGridEhFindDlg_Close = 'Ёпиш'
  DBGridEhFindDlg_FromAnyPart = 'Майдоннинг истаган қисмидан'
  DBGridEhFindDlg_WholeField = 'Майдонни бир бутун олиш'
  DBGridEhFindDlg_FromBeginning = 'Майдонни бошидан'
  DBGridEhFindDlg_Direction_Up = 'Тепага'
  DBGridEhFindDlg_Direction_Down = 'Пастга'
  DBGridEhFindDlg_Direction_All = 'Барча'
  DBGridEhFindDlg_MatchCase = '&Харф шаклини эътиборга олиб'
  DBGridEhFindDlg_MatchFormat = 'Харф &форматини эътиборга олиб'
  DBGridEhFindDlg_TreeRange_InAllNodes = 'Барча шажарада '
  DBGridEhFindDlg_TreeRange_InExpandedNodes = 'Очиқ шажарада'
  DBGridEhFindDlg_TreeRange_InCurrentLevel = 'Жорий қатламда'
  DBGridEhFindDlg_TreeRange_InCurrentNode = 'Жорий шажарада'

  PrintPageSetupDialog_Caption = 'Параметры страницы'
  PrintPageSetupDialog_Page = 'Страница'
  PrintPageSetupDialog_Orientation = 'Ориентация'
  PrintPageSetupDialog_Scaling = 'Масштаб'
  PrintPageSetupDialog_Portrait = 'Книжная'
  PrintPageSetupDialog_Landscape = 'Альбомная'
  PrintPageSetupDialog_PrNormalSize =  '% от натуральной величины'
  PrintPageSetupDialog_PageWideBy = 'стр. в ширину'
  PrintPageSetupDialog_tall = 'в высоту'
  PrintPageSetupDialog_AdjustTo = 'Установить'
  PrintPageSetupDialog_FitTo = 'Разместить не более чем на'
  PrintPageSetupDialog_Margins = 'Поля'
  PrintPageSetupDialog_Left = 'Слева'
  PrintPageSetupDialog_Top = 'Сверху'
  PrintPageSetupDialog_Bottom = 'Снизу'
  PrintPageSetupDialog_Right = 'Справа'
  PrintPageSetupDialog_Header = 'Верхний колонтитул'
  PrintPageSetupDialog_Footer = 'Нижний колонтитул'
  PrintPageSetupDialog_HeaderFooter = 'Колонтитулы'
  PrintPageSetupDialog_ChangeFont = 'Изменить шрифт'
  PrintPageSetupDialog_FontAbr = 'Шфт'
  PrintPageSetupDialog_InsertPageNo_Hint = 'Вставить номер страницы'
  PrintPageSetupDialog_InsertPageNo_Abr = 'Нс'
  PrintPageSetupDialog_InsertPages_Hint = 'Вставить количество страниц'
  PrintPageSetupDialog_InsertPages_Abr = 'Кст'
  PrintPageSetupDialog_InsertDate_Hint = 'Вставить дату'
  PrintPageSetupDialog_InsertDate_Abr = 'Д'
  PrintPageSetupDialog_InsertShortDate_Hint = 'Вставить короткую дату'
  PrintPageSetupDialog_InsertShortDate_Abr = 'Дкр'
  PrintPageSetupDialog_InsertLongDate_Hint = 'Вставить длинную дату'
  PrintPageSetupDialog_InsertLongDate_Abr = 'Ддл'
  PrintPageSetupDialog_InsertTime_Hint = 'Вставить время'
  PrintPageSetupDialog_InsertTime_Abr = 'В'
  PrintPageSetupDialog_PageHeader = 'Верхний колонтитул'
  PrintPageSetupDialog_PageFooter = 'Нижний колонтитул'
  PrintPageSetupDialog_Center = 'По центру'

end
