object EhLibLanguageConsts: TEhLibLanguageConsts_DUT
  Language = 'Nederlands'

  ClearSelectedCells = 'Geselecteerde cellen leegmaken?'
  InvalidTextFormat = 'Ongeldig tekstformaat'
  InvalidVCLDBIFFormat = 'Ongeldig VCLDBIF formaat'
  ErrorDuringInsertValue = 'Fout bij toevoegen van waarde:'
  IgnoreError = 'Fout negeren?'
  TabularInformation = 'Tabelinformatie'
  PageOfPages = 'Pagina %d van %d'
  Preview = 'Voorbeeld'
  FieldNameNotFound = 'Veldnaam ''%s'' niet gevonden'
  FindDialogStringNotFoundMessage = 'String "%s" niet gevonden.'
  VisibleColumns = 'Zichtbare kolommen'
  Cut = 'Knippen'
  Copy = 'Kopiëren'
  Paste = 'Plakken'
  Delete = 'Verwijderen'
  SelectAll = 'Alles selecteren'

  STFilterListItem_Empties = 'Leeg'
  STFilterListItem_NotEmpties = 'Niet leeg'
  STFilterListItem_All = 'Alles'
  STFilterListItem_SelectAll = 'Selecteer Alles'
  STFilterListItem_ClearFilter = 'Filter leegmaken'
  STFilterListItem_ClearFilterInColumn = 'Kolomfilter leegmaken'
  STFilterListItem_SortingByAscend = 'Sorteer oplopend'
  STFilterListItem_SortingByDescend = 'Sorteer aflopend'
  STFilterListItem_ApplyFilter = 'Filter toepassen'
  STFilterListItem_CustomFilter = 'Gepersonaliseerd...'
  STFilterListItem_ShowFilterWindow = 'Show filter window ...'
  STFilterListItem_HideSelectedColumns = 'Hide selected columns'
  STFilterListItem_HideColumn = 'Hide column'

  SimpFilter_equals              = 'gelijk'
  SimpFilter_does_not_equal      = 'niet gelijk'
  SimpFilter_is_greater_than      = 'is groter dan'
  SimpFilter_is_greater_than_or_equal_to = 'is groter dan of gelijk aan'
  SimpFilter_is_less_than        = 'is kleiner dan'
  SimpFilter_is_less_than_or_equal_to = 'is kleiner dan of gelijk aan'
  SimpFilter_begins_with         = 'begint met'
  SimpFilter_does_not_begin_with = 'begint niet met'
  SimpFilter_ends_with           = 'eindigt op'
  SimpFilter_does_not_end_with   = 'eindigt niet op'
  SimpFilter_contains            = 'bevat'
  SimpFilter_does_not_contain    = 'bevat niet'
  SimpFilter_like                = 'zoals'
  SimpFilter_not_like            = 'niet zoals'
  SimpFilter_in_list             = 'in lijst'
  SimpFilter_not_in_list         = 'niet in lijst'
  SimpFilter_is_blank            = 'is leeg'
  SimpFilter_is_not_blank        = 'is niet leeg'

  GroupingPanelText = 'Sleep een kolomhoofding hier om op deze kolom te groeperen'

  NoDataEh = '<Geen gegevens>'
  CalculatorError = 'Fout'

  QuoteIsAbsentEh = 'Quote is niet beschikbaar: '
  LeftBracketExpectedEh = '''('' verwacht: '
  RightBracketExpectedEh = ''')'' verwacht: '
  ErrorInExpressionEh = 'Fout in de uitdrukking: '
  UnexpectedExpressionBeforeNullEh = 'Onverwachte expressie voor Null: '
  UnexpectedExpressionAfterOperatorEh = 'Onverwachte expressie na operator: '
  IncorrectExpressionEh = 'Ongeldige expressie: '
  UnexpectedANDorOREh = 'Onverwachte AND of OR: '

  GridSelectionInfo_Sum = 'Som'
  GridSelectionInfo_Cnt = 'Count'
  GridSelectionInfo_Evg = 'Gemiddelde'
  GridSelectionInfo_Min = 'Min'
  GridSelectionInfo_Max = 'Max'
  CellCountEh = 'Cellen tellen'

  DBGridEhGroupingFooter_Sum = 'Sum'
  DBGridEhGroupingFooter_Count = 'Count'
  DBGridEhGroupingFooter_Avg = 'Average'
  DBGridEhGroupingFooter_Max = 'Max'
  DBGridEhGroupingFooter_Min = 'Min'
  DBGridEhGroupingFooter_Empty = '(Leeg)'

  FirstRecordEh = 'Eerste record'
  PriorRecordEh = 'Vorig record'
  NextRecordEh = 'Volgend record'
  LastRecordEh = 'Laatste record'
  InsertRecordEh = 'Record toevoegen'
  DeleteRecordEh = 'Record verwijderen'
  EditRecordEh = 'Record aanpassen'
  PostEditEh = 'Wijzigingen wegschrijven'
  CancelEditEh = 'Wijzigingen annuleren'
  ConfirmCaptionEh = 'Bevestig'
  RefreshRecordEh = 'Gegevens bijwerken'

  DeleteMultipleRecordsQuestionEh = '%d geselecteerde recorde verwijderen?'
  DeleteAllRecordsQuestionEh = 'Alle records verwijderen?'

  DuplicateVarNameEh = 'Een variabele ''%s'' bestaat reeds in de collectie'

  SearchPanelEditorPromptText = 'Zoeken...'
  UnsupportedFieldTypeEh = 'Niet ondersteund veldtype (%s) voor veld %s'

  SearchPanelApplyFilterEh = 'Records tonen waar de tekst gevonden werd'
  SearchPanelCancelFilterEh = 'Fileter annuleren en zoektekst leegmaken'
  SearchPanelFindNextEh = 'Zoek volgende'
  SearchPanelFindPrevEh = 'Zoek vorige'
  SearchPanelOptionsEh = 'Toon zoekopties'

  SortingByThisColumnIsNotPossibleEh = 'Sorteren op deze kolom is niet mogelijk'
  GroupingByThisColumnIsNotPossibleEh = 'Groeperen op deze kolom is niet mogelijk'

  FindItemNameAllEh = '<Alles>'

  ElapsedTimeEh = 'Verlopen tijd'
  PivotDataBuildingInProgressEh = 'Pivot data wordt aangemaakt...'
  PressESCToCancelEh = 'Druk ESC om te annuleren'

  GrandTotalEh = 'Eindtotaal'
  TotalEh = 'Totaal'
  PivotValueFieldDisplayNameEh = '(Waarde)'
  PivotRowsEh = 'Rijen'
  PivotColumnsEh = 'Kolommen'
  PivotValuesEh = 'Waardes'
  PivotDataIsNotLoadedEh = '<Gegegevsn zijn niet geladen>'

  PivotSliceNonDisplayNameEh = 'Neen'
  PivotSliceYearDisplayNameEh = 'Jaar'
  PivotSliceQuarterDisplayNameEh = 'Kwartaal'
  PivotSliceMonthDisplayNameEh = 'Maand'
  PivotSliceWeekDisplayNameEh = 'Week'
  PivotSliceDayDisplayNameEh = 'Dag'
  PivotSliceHourDisplayNameEh = 'Uur'
  PivotSliceMinDisplayNameEh = 'Min'
  PivotSliceSecDisplayNameEh = 'Sec'
  PivotSliceMSecDisplayNameEh = 'MSec'

  PivotSumFunctionNon = 'Neen'
  PivotSumFunctionSum = 'Som'
  PivotSumFunctionCount = 'Count'
  PivotSumFunctionAvg = 'Gem'
  PivotSumFunctionMax = 'Max'
  PivotSumFunctionMin = 'Min'
  PivotSumFunctionCountDistinct = 'Aantal verschillende'
  PivotSumFunctionProduct = 'Product'
  PivotSumFunctionStDev = 'StAfw'
  PivotSumFunctionStDevp = 'StAfwp'
  PivotSumFunctionVar = 'Var'
  PivotSumFunctionVarp = 'Varp'
  PivotSumFunctionCustom = 'Eigen'

  PlannerResourceUnassignedEh = 'Niet toegekend'
  PlannerNextEventEh = 'Volgend event'
  PlannerPriorEventEh = 'Vorig event'
  PlannerDeletePlanItemEh = 'Event verwijderen?'
  PlannerPeriodFromEh = 'Van'
  PlannerPeriodToEh = 'Tot'
  PlannerWeekTextEh = 'WEEK'
  PlannerEndTimeBeforeStartTimeEh = 'Het einde is voor het begin'

  OKButtonEh = 'OK'
  CancelButtonEh = 'Annuleren'

  GridLoadingModeTextEh = 'Laden...'

  SearchScopeEh = 'Zoek in Scope'
  CurrentColumnEh = 'Huidige Kolom'
  TheEntireGridEh = 'Hele tabel'
  CaseSensitiveEh = 'Hoofdlettergevoelig'
  WholeWordsEh = 'Hele woorden'
  BeginsWithEh = 'Begint met'
  CloseInBracketsEh = '(Sluiten)'

  LabelColumnEh = 'Label Kolom'
  DataColumnEh = 'Data Kolom'

  TodayEh = 'Vandaag'

  PreviewForm_Caption = 'Voorbeeld'
  PreviewForm_Print_Hint = 'Printen'
  PreviewForm_Print_Caption = 'Printen'
  PreviewForm_PrinterSetupDialog_Hint = 'Printer setup'
  PreviewForm_PrinterSetupDialog_Caption = 'Printer setup'
  PreviewForm_Scale_Hint = 'Schaal'
  PreviewForm_Scale_Caption = 'Schaal'
  PreviewForm_PrevPage_Hint = 'Vorige pagina'
  PreviewForm_PrevPage_Caption = 'Vorige'
  PreviewForm_NextPage_Hint = 'Volgende pagina'
  PreviewForm_NextPage_Caption = 'Volgende'
  PreviewForm_Stop_Caption = 'Stop'
  PreviewForm_Close_Hint = 'Voorbeeld sluiten'
  PreviewForm_Close_Caption = 'Sluiten'
  PreviewForm_MenuPageWidth = 'Paginabreedte'
  PreviewForm_MenuFullPage = 'Hele pagina'

  PrnDBGridEhSetupDialog_Caption = 'Printer setup'
  PrnDBGridEhSetupDialog_Margins = '&Marges '
  PrnDBGridEhSetupDialog_Top = '&Boven'
  PrnDBGridEhSetupDialog_Bottom = '&Onder'
  PrnDBGridEhSetupDialog_Left = '&Links'
  PrnDBGridEhSetupDialog_Right = '&Rechts'
  PrnDBGridEhSetupDialog_StretchLongLines = '&Stretch long lines'
  PrnDBGridEhSetupDialog_PrinterSetup = '&Printer setup'
  PrnDBGridEhSetupDialog_Colored = '&Gekleurd'
  PrnDBGridEhSetupDialog_ScaleWholeGrid = 'Hele &tabel schalen'
  PrnDBGridEhSetupDialog_ChangeColumnWidths = 'Kolombreedte aanpassen'
  PrnDBGridEhSetupDialog_FitWidthToPage = 'Breedte op één pagina passen'
  PrnDBGridEhSetupDialog_OptimalColWidths = 'Optilmale kolombreedtes'

  PlannerItemForm_Caption = 'Planner Item'
  PlannerItemForm_Item_Title = 'Titel:'
  PlannerItemForm_Item_StartTime = 'Begintijd:'
  PlannerItemForm_Item_EndTime = 'Eindtijd:'
  PlannerItemForm_AllDayCheck = 'Hele dag event'
  PlannerItemForm_Resource = 'Bron:'

  PictureEditorDialog_Caption = 'Afbeeldingseditor'
  PictureEditorDialog_Load = '&Laden...'
  PictureEditorDialog_Save = '&Opslaan...'
  PictureEditorDialog_Clear = '&Leegmaken'
  PictureEditorDialog_Cut = 'Knippen'
  PictureEditorDialog_Copy = 'Kopiëren'
  PictureEditorDialog_Paste = 'Plakken'
  PictureEditorDialog_ZoomIn = 'Zoom In'
  PictureEditorDialog_ZoomOut = 'Zoom Uit'
  PictureEditorDialog_Reset = 'Herstellen'

  EditPivotField_Caption = 'Samenvattingsfunctie'
  EditPivotField_AggrFunc = 'Samenvattingsfunctie:'
  EditPivotField_DisplayFormat = 'Weergaveformaat:'

  DBGridEhSimpleFilterDialog_Caption = 'Aangepaste filter'
  DBGridEhSimpleFilterDialog_ShowRecordsWhere = 'Toon records waar:'
  DBGridEhSimpleFilterDialog_OneCharWildcardInfo = 'Gebruik "_" om één enkel karater voor te stellen'
  DBGridEhSimpleFilterDialog_SeveralCharsWildcardInfo = 'Gebruik "%" om een reeks karakters voor te stellen'
  DBGridEhSimpleFilterDialog_Or_Caption = '&Or'
  DBGridEhSimpleFilterDialog_And_Caption = '&And'

  DBGridEhFindDlg_Caption = 'Zoek tekst'
  DBGridEhFindDlg_FindWhat = 'Vind wat:'
  DBGridEhFindDlg_FindIn = 'Vind in:'
  DBGridEhFindDlg_Match = 'Matc&h:'
  DBGridEhFindDlg_Search = 'Zoek:'
  DBGridEhFindDlg_FindInTree = 'Zoek in boom:'
  DBGridEhFindDlg_FindNext = 'Zoek volgende'
  DBGridEhFindDlg_Close = 'Sluiten'
  DBGridEhFindDlg_FromAnyPart = 'Van elk veldsdeel'
  DBGridEhFindDlg_WholeField = 'Heel veld'
  DBGridEhFindDlg_FromBeginning = 'Van begin van het veld'
  DBGridEhFindDlg_Direction_Up = 'Omhoog'
  DBGridEhFindDlg_Direction_Down = 'Omlaag'
  DBGridEhFindDlg_Direction_All = 'Alles'
  DBGridEhFindDlg_MatchCase = 'Overeenkomende Case'
  DBGridEhFindDlg_MatchFormat = 'Overeenkomend formaat'
  DBGridEhFindDlg_TreeRange_InAllNodes = 'In alle nodes'
  DBGridEhFindDlg_TreeRange_InExpandedNodes = 'In uitegvoerde nodes'
  DBGridEhFindDlg_TreeRange_InCurrentLevel = 'In huidig niveau'
  DBGridEhFindDlg_TreeRange_InCurrentNode = 'In huidige node'

  PrintPageSetupDialog_Caption = 'Paginasetup'
  PrintPageSetupDialog_Page = 'Pagina'
  PrintPageSetupDialog_Orientation = 'Orientatie'
  PrintPageSetupDialog_Scaling = 'Schaling'
  PrintPageSetupDialog_Portrait = 'Staand'
  PrintPageSetupDialog_Landscape = 'Liggend'
  PrintPageSetupDialog_PrNormalSize =  '% van normale grootte'
  PrintPageSetupDialog_PageWideBy = 'pagina(s) breedte'
  PrintPageSetupDialog_tall = 'hoog'
  PrintPageSetupDialog_AdjustTo = 'Aanpassen tot'
  PrintPageSetupDialog_FitTo = 'Passen op'
  PrintPageSetupDialog_Margins = 'Marges'
  PrintPageSetupDialog_Left = 'Liks'
  PrintPageSetupDialog_Top = 'Boven'
  PrintPageSetupDialog_Bottom = 'Onder'
  PrintPageSetupDialog_Right = 'Rechts'
  PrintPageSetupDialog_Header = 'Koptekst'
  PrintPageSetupDialog_Footer = 'Voettekst'
  PrintPageSetupDialog_HeaderFooter = 'Koptekst/Voettekst'
  PrintPageSetupDialog_ChangeFont = 'Font aanpassen'
  PrintPageSetupDialog_FontAbr = 'F'
  PrintPageSetupDialog_InsertPageNo_Hint = 'Paginanummer invoegen'
  PrintPageSetupDialog_InsertPageNo_Abr = 'Pn'
  PrintPageSetupDialog_InsertPages_Hint = 'Paginas invoegen'
  PrintPageSetupDialog_InsertPages_Abr = 'Ps'
  PrintPageSetupDialog_InsertDate_Hint = 'Datum invoegen'
  PrintPageSetupDialog_InsertDate_Abr = 'D'
  PrintPageSetupDialog_InsertShortDate_Hint = 'Korte datum invoegen'
  PrintPageSetupDialog_InsertShortDate_Abr = 'Ds'
  PrintPageSetupDialog_InsertLongDate_Hint = 'Lange datum invoegen'
  PrintPageSetupDialog_InsertLongDate_Abr = 'Dl'
  PrintPageSetupDialog_InsertTime_Hint = 'Tijd invoegen'
  PrintPageSetupDialog_InsertTime_Abr = 'T'
  PrintPageSetupDialog_PageHeader = 'Pagina koptekst'
  PrintPageSetupDialog_PageFooter = 'Pagina voettekst'
  PrintPageSetupDialog_Center = 'Centreren'

  CustomizeColumnsDialog = 'Kolommen aanpassen ...'
  DBGridEhCustomizeColumnsDialog_VisibleColumns = 'Zichtbare kolommen'
  DBGridEhCustomizeColumnsDialog_HiddenColumns = 'Verborgen kolommen'
  DBGridEhCustomizeColumnsDialog_Caption = 'Kolomsetup'
  DBGridEhCustomizeColumnsDialog_ColumnName = 'Naam'
  DBGridEhCustomizeColumnsDialog_ColumnWidth = 'Breedte'
  DBGridEhCustomizeColumnsDialog_SetWidth_Hint = 'Zet breedte'
  DBGridEhCustomizeColumnsDialog_MoveUp_Hint = 'Omhoog'
  DBGridEhCustomizeColumnsDialog_MoveDown_Hint = 'Omlaag'
  DBGridEhCustomizeColumnsDialog_Hide_Hint = 'Verbergen'
  DBGridEhCustomizeColumnsDialog_Show_Hint = 'Tonen'
  DBGridEhCustomizeColumnsDialog_EnterNumericalValue = 'Een cijfer invoeren'
  DBGridEhCustomizeColumnsDialog_EnterColumnWidthS = 'Kolombreedte(n)'

  FilterListValuesLimitExceeded = 'Te veel waarden geselecteerd.'#13#10'Het aantal geselecteerde waarden mag %d niet overstijgen'
end