object EhLibLanguageConsts: TEhLibLanguageConsts_ITA
  Language = 'Italiano'

  ClearSelectedCells = 'Svuoto le celle selezionate?'
  InvalidTextFormat = 'Formato testo non valido'
  InvalidVCLDBIFFormat = 'Formato VCLDBIF non valido'
  ErrorDuringInsertValue = 'Errore inserendo un valore:'
  IgnoreError = 'Ignoro l''errore?'
  TabularInformation = 'Informazioni tabulari'
  PageOfPages = 'Pagina %d di %d'
  Preview = 'Anteprima'
  FieldNameNotFound = 'Non trovo il campo di nome ''%s'''
  FindDialogStringNotFoundMessage = 'Non trovo la stringa "%s".'
  VisibleColumns = 'Colonne visibili'
  Cut = 'Taglia'
  Copy = 'Copia'
  Paste = 'Incolla'
  Delete = 'Cancella'
  SelectAll = 'Scegli tutto'

  STFilterListItem_Empties = 'Vuoto'
  STFilterListItem_NotEmpties = 'Non vuoto'
  STFilterListItem_All = 'Tutto'
  STFilterListItem_SelectAll = 'Scegli tutto'
  STFilterListItem_ClearFilter = 'Elimina filtro'
  STFilterListItem_ClearFilterInColumn = 'Annulla filtro di colonna'
  STFilterListItem_SortingByAscend = 'Ordinamento ascendente'
  STFilterListItem_SortingByDescend = 'Ordinamento discendente'
  STFilterListItem_ApplyFilter = 'Applica filtro '
  STFilterListItem_CustomFilter = 'Personalizzato...'
  STFilterListItem_ShowFilterWindow = 'Show filter window ...'
  STFilterListItem_HideSelectedColumns = 'Hide selected columns'
  STFilterListItem_HideColumn = 'Hide column'

  SimpFilter_equals              = 'uguale'
  SimpFilter_does_not_equal      = 'diverso'
  SimpFilter_is_greater_than      = 'maggiore di'
  SimpFilter_is_greater_than_or_equal_to = 'maggiore o uguale a'
  SimpFilter_is_less_than        = 'minore di'
  SimpFilter_is_less_than_or_equal_to = 'minore o uguale a'
  SimpFilter_begins_with         = 'comincia con'
  SimpFilter_does_not_begin_with = 'non comincia con'
  SimpFilter_ends_with           = 'finisce con'
  SimpFilter_does_not_end_with   = 'non finisce con'
  SimpFilter_contains            = 'contiene'
  SimpFilter_does_not_contain    = 'non contiene'
  SimpFilter_like                = 'simile'
  SimpFilter_not_like            = 'non simile'
  SimpFilter_in_list             = 'in lista'
  SimpFilter_not_in_list         = 'non in lista'
  SimpFilter_is_blank            = 'è vuoto'
  SimpFilter_is_not_blank        = 'non è vuoto'

  GroupingPanelText = 'Trascina qui una intestazione di colonna per raggruppare per quella colonna'

  NoDataEh = '<Nessun record>'
  CalculatorError = 'Errore'

  QuoteIsAbsentEh = 'Manca una virgoletta: '
  LeftBracketExpectedEh = '''('' attesa: '
  RightBracketExpectedEh = ''')'' attesa: '
  ErrorInExpressionEh = 'Errore in espressione: '
  UnexpectedExpressionBeforeNullEh = 'Espressione inattesa prima di Null: '
  UnexpectedExpressionAfterOperatorEh = 'Espressione inattesa dopo operatore: '
  IncorrectExpressionEh = 'Espressione non corretta: '
  UnexpectedANDorOREh = 'AND o OR inatteso: '

  GridSelectionInfo_Sum = 'Somma'
  GridSelectionInfo_Cnt = 'Conta'
  GridSelectionInfo_Evg = 'Media'
  GridSelectionInfo_Min = 'Min'
  GridSelectionInfo_Max = 'Max'
  CellCountEh = 'Conta le celle'

  DBGridEhGroupingFooter_Sum = 'Somma'
  DBGridEhGroupingFooter_Count = 'Conta'
  DBGridEhGroupingFooter_Avg = 'Media'
  DBGridEhGroupingFooter_Max = 'Max'
  DBGridEhGroupingFooter_Min = 'Min'
  DBGridEhGroupingFooter_Empty = '(Vuoto)'

  FirstRecordEh = 'Primo record'
  PriorRecordEh = 'Record precedente'
  NextRecordEh = 'Prossimo record'
  LastRecordEh = 'Ultimo record'
  InsertRecordEh = 'Inserisci record'
  DeleteRecordEh = 'Cancella record'
  EditRecordEh = 'Modifica record'
  PostEditEh = 'Salva modifica'
  CancelEditEh = 'Annulla modifica'
  ConfirmCaptionEh = 'Conferma'
  RefreshRecordEh = 'Rileggi dati'

  DeleteMultipleRecordsQuestionEh = 'Cancello %d record selezionati?'
  DeleteAllRecordsQuestionEh = 'Cancello tutti i record?'

  DuplicateVarNameEh = 'Una variable di nome ''%s'' esiste già nella Collezione'

  SearchPanelEditorPromptText = 'Cerca...'
  UnsupportedFieldTypeEh = 'Tipo campo non supportato (%s) per il campo %s'

  SearchPanelApplyFilterEh = 'Mostra record contenenti il testo'
  SearchPanelCancelFilterEh = 'Elimina il filtro e il testo da cercare'
  SearchPanelFindNextEh = 'Trova prossimo'
  SearchPanelFindPrevEh = 'Trova precedente'
  SearchPanelOptionsEh = 'Mostra opzioni di ricerca'

  SortingByThisColumnIsNotPossibleEh = 'Ordinamento impossibile su questa colonna'
  GroupingByThisColumnIsNotPossibleEh = 'Raggruppamento impossibile su questa colonna'

  FindItemNameAllEh = '<Tutto>'

  ElapsedTimeEh = 'Tempo trascorso'
  PivotDataBuildingInProgressEh = 'Sto preparando i dati per il Pivot...'
  PressESCToCancelEh = 'Premi ESC per annullare'

  GrandTotalEh = 'Totale generale'
  TotalEh = 'Totale'
  PivotValueFieldDisplayNameEh = '(Valore)'
  PivotRowsEh = 'Righe'
  PivotColumnsEh = 'Colonne'
  PivotValuesEh = 'Valori'
  PivotDataIsNotLoadedEh = '<Dati non caricati>'

  PivotSliceNonDisplayNameEh = 'No'
  PivotSliceYearDisplayNameEh = 'Anno'
  PivotSliceQuarterDisplayNameEh = 'Trimestre'
  PivotSliceMonthDisplayNameEh = 'Mese'
  PivotSliceWeekDisplayNameEh = 'Settimana'
  PivotSliceDayDisplayNameEh = 'Giorno'
  PivotSliceHourDisplayNameEh = 'Ora'
  PivotSliceMinDisplayNameEh = 'Min'
  PivotSliceSecDisplayNameEh = 'Sec'
  PivotSliceMSecDisplayNameEh = 'MSec'

  PivotSumFunctionNon = 'No'
  PivotSumFunctionSum = 'Somma'
  PivotSumFunctionCount = 'Conta'
  PivotSumFunctionAvg = 'Media'
  PivotSumFunctionMax = 'Max'
  PivotSumFunctionMin = 'Min'
  PivotSumFunctionCountDistinct = 'Conta Distinct'
  PivotSumFunctionProduct = 'Prodotto'
  PivotSumFunctionStDev = 'StDev'
  PivotSumFunctionStDevp = 'StDevp'
  PivotSumFunctionVar = 'Var'
  PivotSumFunctionVarp = 'Varp'
  PivotSumFunctionCustom = 'Custom'

  PlannerResourceUnassignedEh = 'Non assegnato'
  PlannerNextEventEh = 'Prossimo evento'
  PlannerPriorEventEh = 'Evento precedente'
  PlannerDeletePlanItemEh = 'Cancello l''evento?'
  PlannerPeriodFromEh = 'Da'
  PlannerPeriodToEh = 'A'
  PlannerWeekTextEh = 'Sett.'
  PlannerEndTimeBeforeStartTimeEh = 'L''ora finale è prima di quella iniziale'

  OKButtonEh = 'OK'
  CancelButtonEh = 'Annulla'

  GridLoadingModeTextEh = 'Carico...'

  SearchScopeEh = 'Cerca in'
  CurrentColumnEh = 'colonna corrente'
  TheEntireGridEh = 'intera griglia'
  CaseSensitiveEh = 'Distingui maiuscole/minuscole'
  WholeWordsEh = 'Parole intere'
  BeginsWithEh = 'Comincia con'
  CloseInBracketsEh = '(Chiudi)'

  LabelColumnEh = 'Colonna etichetta'
  DataColumnEh = 'Colonna dati'

  TodayEh = 'Oggi'

  PreviewForm_Caption = 'Anteprima'
  PreviewForm_Print_Hint = 'Stampa'
  PreviewForm_Print_Caption = 'Stampa'
  PreviewForm_PrinterSetupDialog_Hint = 'Setup stampante'
  PreviewForm_PrinterSetupDialog_Caption = 'Setup stampante'
  PreviewForm_Scale_Hint = 'Dimensione'
  PreviewForm_Scale_Caption = 'Dimensione'
  PreviewForm_PrevPage_Hint = 'Pagina precedente'
  PreviewForm_PrevPage_Caption = 'Indietro'
  PreviewForm_NextPage_Hint = 'Prossima pagina'
  PreviewForm_NextPage_Caption = 'Avanti'
  PreviewForm_Stop_Caption = 'Stop'
  PreviewForm_Close_Hint = 'Chiudi anteprima'
  PreviewForm_Close_Caption = 'Chiudi'
  PreviewForm_MenuPageWidth = 'Ampiezza pagina'
  PreviewForm_MenuFullPage = 'Pagina intera'

  PrnDBGridEhSetupDialog_Caption = 'Impostazioni stampante'
  PrnDBGridEhSetupDialog_Margins = '&Margini '
  PrnDBGridEhSetupDialog_Top = 'S&opra'
  PrnDBGridEhSetupDialog_Bottom = '&Sotto'
  PrnDBGridEhSetupDialog_Left = 'S&inistra'
  PrnDBGridEhSetupDialog_Right = '&Destra'
  PrnDBGridEhSetupDialog_StretchLongLines = '&Adatta righe lunghe'
  PrnDBGridEhSetupDialog_PrinterSetup = 'S&etup stampante'
  PrnDBGridEhSetupDialog_Colored = '&Colorato'
  PrnDBGridEhSetupDialog_ScaleWholeGrid = 'Scala intera &griglia'
  PrnDBGridEhSetupDialog_ChangeColumnWidths = 'C&ambia ampiezza colonne'
  PrnDBGridEhSetupDialog_FitWidthToPage = 'A&datta larghezza ad una pagina'
  PrnDBGridEhSetupDialog_OptimalColWidths = 'Ampie&zza colonne ottimale'

  PlannerItemForm_Caption = 'Evento agenda'
  PlannerItemForm_Item_Title = 'Titolo:'
  PlannerItemForm_Item_StartTime = 'Ora inizio:'
  PlannerItemForm_Item_EndTime = 'Ora fine:'
  PlannerItemForm_AllDayCheck = 'Evento giornata intera'
  PlannerItemForm_Resource = 'Risorsa:'

  PictureEditorDialog_Caption = 'Editor immagini'
  PictureEditorDialog_Load = '&Carica...'
  PictureEditorDialog_Save = '&Salva...'
  PictureEditorDialog_Clear = '&Elimina'
  PictureEditorDialog_Cut = 'Taglia'
  PictureEditorDialog_Copy = 'Copia'
  PictureEditorDialog_Paste = 'Incolla'
  PictureEditorDialog_ZoomIn = 'Zoom In'
  PictureEditorDialog_ZoomOut = 'Zoom Out'
  PictureEditorDialog_Reset = 'Reset'

  EditPivotField_Caption = 'Funzione sommario'
  EditPivotField_AggrFunc = 'Funzione:'
  EditPivotField_DisplayFormat = 'Formato visualizzazione:'

  DBGridEhSimpleFilterDialog_Caption = 'Filtro personalizzato'
  DBGridEhSimpleFilterDialog_ShowRecordsWhere = 'Mostra record dove:'
  DBGridEhSimpleFilterDialog_OneCharWildcardInfo = 'Usa "_" per rappresentare un singolo carattere'
  DBGridEhSimpleFilterDialog_SeveralCharsWildcardInfo = 'Usa "%" per rappresentare una stringa di caratteri'
  DBGridEhSimpleFilterDialog_Or_Caption = '&Or'
  DBGridEhSimpleFilterDialog_And_Caption = '&And'

  DBGridEhFindDlg_Caption = 'Trova testo'
  DBGridEhFindDlg_FindWhat = 'Co&sa cerco:'
  DBGridEhFindDlg_FindIn = 'Trova &in:'
  DBGridEhFindDlg_Match = 'Corrisponden&za:'
  DBGridEhFindDlg_Search = 'Ce&rca:'
  DBGridEhFindDlg_FindInTree = 'Trova nell''albero:'
  DBGridEhFindDlg_FindNext = 'Trova &prossimo'
  DBGridEhFindDlg_Close = 'Chiudi'
  DBGridEhFindDlg_FromAnyPart = 'In qualunque parte del campo'
  DBGridEhFindDlg_WholeField = 'Campo intero'
  DBGridEhFindDlg_FromBeginning = 'All''inizio del campo'
  DBGridEhFindDlg_Direction_Up = 'Su'
  DBGridEhFindDlg_Direction_Down = 'Giù'
  DBGridEhFindDlg_Direction_All = 'Tutto'
  DBGridEhFindDlg_MatchCase = '&Considera maiuscolo/minuscolo'
  DBGridEhFindDlg_MatchFormat = 'Considera il f&ormato'
  DBGridEhFindDlg_TreeRange_InAllNodes = 'In tutti i nodi'
  DBGridEhFindDlg_TreeRange_InExpandedNodes = 'Nei nodi espansi'
  DBGridEhFindDlg_TreeRange_InCurrentLevel = 'Nel livello corrente'
  DBGridEhFindDlg_TreeRange_InCurrentNode = 'Nel nodo corrente'

  PrintPageSetupDialog_Caption = 'Imposta pagina'
  PrintPageSetupDialog_Page = 'Pagina'
  PrintPageSetupDialog_Orientation = 'Orientamento'
  PrintPageSetupDialog_Scaling = 'Scalatura'
  PrintPageSetupDialog_Portrait = 'Verticale'
  PrintPageSetupDialog_Landscape = 'Orizzontale'
  PrintPageSetupDialog_PrNormalSize =  '% dimensione normale'
  PrintPageSetupDialog_PageWideBy = 'pagine larghe'
  PrintPageSetupDialog_tall = 'alte'
  PrintPageSetupDialog_AdjustTo = 'Adatta a'
  PrintPageSetupDialog_FitTo = 'Adatta a'
  PrintPageSetupDialog_Margins = 'Margini'
  PrintPageSetupDialog_Left = 'Sinistra'
  PrintPageSetupDialog_Top = 'Sopra'
  PrintPageSetupDialog_Bottom = 'Sotto'
  PrintPageSetupDialog_Right = 'Destra'
  PrintPageSetupDialog_Header = 'Intestazione'
  PrintPageSetupDialog_Footer = 'Piè pagina'
  PrintPageSetupDialog_HeaderFooter = 'Intestazione/Piè pagina'
  PrintPageSetupDialog_ChangeFont = 'Cambia font'
  PrintPageSetupDialog_FontAbr = 'F'
  PrintPageSetupDialog_InsertPageNo_Hint = 'Inserisci numero di pagina'
  PrintPageSetupDialog_InsertPageNo_Abr = 'Pn'
  PrintPageSetupDialog_InsertPages_Hint = 'Inserisci pagine'
  PrintPageSetupDialog_InsertPages_Abr = 'Ps'
  PrintPageSetupDialog_InsertDate_Hint = 'Inserisci data'
  PrintPageSetupDialog_InsertDate_Abr = 'D'
  PrintPageSetupDialog_InsertShortDate_Hint = 'Inserisci data breve'
  PrintPageSetupDialog_InsertShortDate_Abr = 'Ds'
  PrintPageSetupDialog_InsertLongDate_Hint = 'Inserisci data lunga'
  PrintPageSetupDialog_InsertLongDate_Abr = 'Dl'
  PrintPageSetupDialog_InsertTime_Hint = 'Inserisci ora'
  PrintPageSetupDialog_InsertTime_Abr = 'T'
  PrintPageSetupDialog_PageHeader = 'Intestazione pagina'
  PrintPageSetupDialog_PageFooter = 'Piè pagina'
  PrintPageSetupDialog_Center = 'Centra'

end