DROP USER UCHET22 CASCADE;

CREATE USER UCHET22
  IDENTIFIED BY <password>
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;

-- 3 Roles for UCHET22 
GRANT CONNECT TO UCHET22;
GRANT DBA TO UCHET22;
GRANT RESOURCE TO UCHET22;
ALTER USER UCHET22 DEFAULT ROLE ALL;

-- 18 System Privileges for UCHET22 
GRANT ALTER ANY MATERIALIZED VIEW TO UCHET22;
GRANT ALTER ANY PROCEDURE TO UCHET22;
GRANT ALTER ANY SEQUENCE TO UCHET22;
GRANT ALTER ANY TABLE TO UCHET22;
GRANT ALTER ANY TRIGGER TO UCHET22;
GRANT CREATE ANY CONTEXT TO UCHET22;
GRANT CREATE ANY INDEX TO UCHET22;
GRANT CREATE ANY INDEXTYPE TO UCHET22;
GRANT CREATE ANY TYPE TO UCHET22;
GRANT CREATE MATERIALIZED VIEW TO UCHET22;
GRANT CREATE PROCEDURE TO UCHET22;
GRANT CREATE SEQUENCE TO UCHET22;
GRANT CREATE TRIGGER TO UCHET22;
GRANT CREATE VIEW TO UCHET22;
GRANT EXECUTE ANY PROCEDURE TO UCHET22;
GRANT SELECT ANY DICTIONARY TO UCHET22;
GRANT SELECT ANY TABLE TO UCHET22;
GRANT UNLIMITED TABLESPACE TO UCHET22;

-- 1 Tablespace Quota for UCHET22 
ALTER USER UCHET22 QUOTA UNLIMITED ON USERS;

-- 52 Object Privileges for UCHET22 
GRANT EXECUTE ON DV.CENANOMBEFOREDATE TO UCHET22;
GRANT EXECUTE ON DV.CENANOMOLD TO UCHET22;
GRANT EXECUTE ON DV.CREATEARTIKUL TO UCHET22;
GRANT DELETE, INSERT, UPDATE ON DV.DEMAND TO UCHET22;
GRANT DELETE, INSERT, UPDATE ON DV.DEMAND_SPEC TO UCHET22;
GRANT EXECUTE ON DV.GETCOUNTRESERV TO UCHET22;
GRANT EXECUTE ON DV.GETRASDELCATALOG TO UCHET22;
GRANT DELETE, INSERT, UPDATE ON DV.NOMENCLATURA TO UCHET22;
GRANT DELETE, INSERT, UPDATE ON DV.NOMENCLATURA_IN_IZDEL TO UCHET22;
GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON DV.PROPERTY_VALUES TO UCHET22;
GRANT EXECUTE ON DV.P_SYNCSPECIZDEL TO UCHET22;
GRANT DELETE, INSERT, UPDATE ON DV.ZAKAZ TO UCHET22;
GRANT EXECUTE ON DV_0805.CENANOMBEFOREDATE TO UCHET22;
GRANT EXECUTE ON DV_0805.GETCOUNTRESERV TO UCHET22;
GRANT EXECUTE ON DV_0805.GETRASDELCATALOG TO UCHET22;
GRANT DELETE, INSERT, UPDATE ON DV_0805.NOMENCLATURA_IN_IZDEL TO UCHET22;
GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON DV_0805.PROPERTY_VALUES TO UCHET22;
GRANT EXECUTE ON DV_0805.P_SYNCSPECIZDEL TO UCHET22;
GRANT EXECUTE ON DV1112.CENANOMBEFOREDATE TO UCHET22;
GRANT EXECUTE ON DV1112.CENANOMOLD TO UCHET22;
GRANT EXECUTE ON DV1112.CREATEARTIKUL TO UCHET22;
GRANT DELETE, INSERT, UPDATE ON DV1112.DEMAND TO UCHET22;
GRANT DELETE, INSERT, UPDATE ON DV1112.DEMAND_SPEC TO UCHET22;
GRANT EXECUTE ON DV1112.GETCOUNTRESERV TO UCHET22;
GRANT EXECUTE ON DV1112.GETRASDELCATALOG TO UCHET22;
GRANT DELETE, INSERT, UPDATE ON DV1112.NOMENCLATURA TO UCHET22;
GRANT DELETE, INSERT, UPDATE ON DV1112.NOMENCLATURA_IN_IZDEL TO UCHET22;
GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON DV1112.PROPERTY_VALUES TO UCHET22;
GRANT EXECUTE ON DV1112.P_SYNCSPECIZDEL TO UCHET22;
GRANT DELETE, INSERT, UPDATE ON DV1112.ZAKAZ TO UCHET22;
GRANT EXECUTE ON DV3108.CENANOMBEFOREDATE TO UCHET22;
GRANT EXECUTE ON DV3108.CENANOMOLD TO UCHET22;
GRANT DELETE, INSERT, UPDATE ON DV3108.DEMAND TO UCHET22;
GRANT DELETE, INSERT, UPDATE ON DV3108.DEMAND_SPEC TO UCHET22;
GRANT EXECUTE ON DV3108.GETCOUNTRESERV TO UCHET22;
GRANT EXECUTE ON DV3108.GETRASDELCATALOG TO UCHET22;
GRANT DELETE, INSERT, UPDATE ON DV3108.NOMENCLATURA TO UCHET22;
GRANT DELETE, INSERT, UPDATE ON DV3108.NOMENCLATURA_IN_IZDEL TO UCHET22;
GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON DV3108.PROPERTY_VALUES TO UCHET22;
GRANT EXECUTE ON DV3108.P_SYNCSPECIZDEL TO UCHET22;
GRANT EXECUTE ON SYS.DBMS_CRYPTO TO UCHET22;
GRANT EXECUTE ON SYS.DBMS_SESSION TO UCHET22;
GRANT EXECUTE, READ, WRITE ON DIRECTORY ORA_EXP_DIR TO UCHET22 WITH GRANT OPTION;
GRANT ALTER, UPDATE ON UCHET.MAILING TO UCHET22;
GRANT DELETE, REFERENCES ON UCHET.TO_ORDERS TO UCHET22;
GRANT DELETE ON UCHET.TO_ORDERS_VERSIONS TO UCHET22;
GRANT DELETE ON UCHET.TO_PASSPORT_ADDCOMPL TO UCHET22;
GRANT DELETE ON UCHET.TO_PASSPORT_ADDINFO TO UCHET22;
GRANT DELETE ON UCHET.TO_PASSPORT_EXTFILES TO UCHET22;
GRANT DELETE ON UCHET.TO_PASSPORT_HEAD TO UCHET22;
GRANT DELETE ON UCHET.TO_PASSPORT_ITEMS TO UCHET22;
GRANT DELETE ON UCHET.TO_PASSPORT_SEMIPRODUCTS TO UCHET22;
