--перенкомпилировать невалидные объекты схемы
begin
  sys.dbms_utility.compile_schema(schema => 'DV');
  -- аргумент compile_all => false (по умолчанию) компилирует только невалидные объекты[reference:4]
end;
/

EXEC DBMS_STATS.GATHER_SCHEMA_STATS('DV');

EXEC sys.dbms_utility.compile_schema(schema => 'DV');
EXEC sys.dbms_utility.compile_schema(schema => 'UCHET22');


ALTER SYSTEM SET DB_FILE_MULTIBLOCK_READ_COUNT = 128 SCOPE=BOTH;

EXEC DBMS_STATS.GATHER_SCHEMA_STATS('DV', OPTIONS => 'GATHER AUTO');


ALTER SESSION SET OPTIMIZER_FEATURES_ENABLE = '11.2.0.4';
select /*+ PARALLEL(6) */ * from dv.V_SPINVOICES;
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY_CURSOR(NULL, NULL, 'ALLSTATS LAST'));

--ALTER SYSTEM SET INMEMORY_SIZE = 2G SCOPE=SPFILE;

alter user UCHET22 identified by UCHET22;

GRANT EXECUTE ON DV.CENANOMBEFOREDATE TO UCHET22;
GRANT EXECUTE ON DV.CENANOMOLD TO UCHET22;
GRANT EXECUTE ON DV.CREATEARTIKUL TO UCHET22;
GRANT DELETE, INSERT, UPDATE ON DV.DEMAND TO UCHET22;
GRANT DELETE, INSERT, UPDATE ON DV.DEMAND_SPEC TO UCHET22;
GRANT EXECUTE ON DV.GETCOUNTRESERV TO UCHET22;
GRANT EXECUTE ON DV.GETRASDELCATALOG TO UCHET22;
GRANT DELETE, INSERT, UPDATE ON DV.NOMENCLATURA TO UCHET22;
GRANT DELETE, INSERT, UPDATE ON DV.NOMENCLATURA_IN_IZDEL TO UCHET22;
GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON DV.PROPERTY_VALUES TO UCHET22;
GRANT EXECUTE ON DV.P_SYNCSPECIZDEL TO UCHET22;
GRANT DELETE, INSERT, UPDATE ON DV.STOCK TO UCHET22;
GRANT DELETE, INSERT, UPDATE ON DV.ZAKAZ TO UCHET22;
GRANT EXECUTE ON SYS.DBMS_CRYPTO TO UCHET22;  --!!!
GRANT EXECUTE ON SYS.DBMS_SESSION TO UCHET22;  --!!!
GRANT EXECUTE ON SYS.KILL_USER_SESSION TO UCHET22;
GRANT EXECUTE, READ, WRITE ON DIRECTORY ORA_EXP_DIR TO UCHET22 WITH GRANT OPTION;
GRANT EXECUTE ON SYSTEM.KILL_USER_SESSION TO UCHET22;


alter user UCHET22 identified by UCHET22_;
alter user DV identified by 111;
alter user UCHET identified by UCHET;
