/*create user uchet22 identified by uchet22 default tablespace users temporary tablespace temp;
DROP USER UCHET22 CASCADE;

CREATE USER UCHET22
  IDENTIFIED BY <password>
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
*/  

-- 3 Roles for UCHET22 
GRANT CONNECT TO UCHET22;
GRANT DBA TO UCHET22;
GRANT RESOURCE TO UCHET22;
ALTER USER UCHET22 DEFAULT ROLE ALL;

-- 17 System Privileges for UCHET22 
GRANT ALTER ANY MATERIALIZED VIEW TO UCHET22;
GRANT ALTER ANY PROCEDURE TO UCHET22;
GRANT ALTER ANY SEQUENCE TO UCHET22;
GRANT ALTER ANY TABLE TO UCHET22;
GRANT ALTER ANY TRIGGER TO UCHET22;
GRANT CREATE ANY CONTEXT TO UCHET22;
GRANT CREATE ANY INDEX TO UCHET22;
GRANT CREATE ANY INDEXTYPE TO UCHET22;
GRANT CREATE ANY TYPE TO UCHET22;
GRANT CREATE MATERIALIZED VIEW TO UCHET22;
GRANT CREATE PROCEDURE TO UCHET22;
GRANT CREATE SEQUENCE TO UCHET22;
GRANT CREATE TRIGGER TO UCHET22;
GRANT CREATE VIEW TO UCHET22;
GRANT EXECUTE ANY PROCEDURE TO UCHET22;
GRANT SELECT ANY DICTIONARY TO UCHET22;
GRANT SELECT ANY TABLE TO UCHET22;
GRANT UNLIMITED TABLESPACE TO UCHET22;

-- 1 Tablespace Quota for UCHET22 
ALTER USER UCHET22 QUOTA UNLIMITED ON USERS;

-- 52 Object Privileges for UCHET22 
GRANT EXECUTE ON DV.CENANOMBEFOREDATE TO UCHET22;
GRANT EXECUTE ON DV.CENANOMOLD TO UCHET22;
GRANT EXECUTE ON DV.CREATEARTIKUL TO UCHET22;
GRANT DELETE, INSERT, UPDATE ON DV.DEMAND TO UCHET22;
GRANT DELETE, INSERT, UPDATE ON DV.DEMAND_SPEC TO UCHET22;
GRANT EXECUTE ON DV.GETCOUNTRESERV TO UCHET22;
GRANT EXECUTE ON DV.GETRASDELCATALOG TO UCHET22;
GRANT DELETE, INSERT, UPDATE ON DV.NOMENCLATURA TO UCHET22;
GRANT DELETE, INSERT, UPDATE ON DV.NOMENCLATURA_IN_IZDEL TO UCHET22;
GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON DV.PROPERTY_VALUES TO UCHET22;
GRANT EXECUTE ON DV.P_SYNCSPECIZDEL TO UCHET22;
GRANT DELETE, INSERT, UPDATE ON DV.ZAKAZ TO UCHET22;
GRANT EXECUTE ON SYS.DBMS_CRYPTO TO UCHET22;
GRANT EXECUTE ON SYS.DBMS_SESSION TO UCHET22;
GRANT EXECUTE, READ, WRITE ON DIRECTORY ORA_EXP_DIR TO UCHET22 WITH GRANT OPTION;
